name: Engine integration request
description: Request a specific engine integration improvement.
title: "[Engine]: "
labels: ["adapter"]
body:
  - type: dropdown
    id: engine
    attributes:
      label: Engine
      options:
        - phaser
        - godot
        - love2d
        - pixi
        - canvas
        - unity
        - other
    validations:
      required: true
  - type: textarea
    id: request
    attributes:
      label: Request
    validations:
      required: true
